<script setup>
import { computed, onBeforeUnmount, reactive, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { IconIdBadge2, IconPlus } from '@tabler/icons-vue'
import AdminDataTable from '../../components/admin/AdminDataTable.vue'
import AdminFilterBar from '../../components/admin/AdminFilterBar.vue'
import AdminPageHeading from '../../components/admin/AdminPageHeading.vue'
import AppAlert from '../../components/ui/AppAlert.vue'
import AppButton from '../../components/ui/AppButton.vue'
import AppCard from '../../components/ui/AppCard.vue'
import AppDrawer from '../../components/ui/AppDrawer.vue'
import AppInput from '../../components/ui/AppInput.vue'
import AppSelect from '../../components/ui/AppSelect.vue'
import AppTextarea from '../../components/ui/AppTextarea.vue'
import AppToast from '../../components/ui/AppToast.vue'
import { useAdminStore } from '../../stores/admin'
import { useAdminManagementStore } from '../../stores/adminManagement'
import { useAdminMembersStore, useAdminMembershipsStore } from '../../stores/adminResources'

const route = useRoute(); const router = useRouter(); const admin = useAdminStore(); const management = useAdminManagementStore(); const memberships = useAdminMembershipsStore(); const members = useAdminMembersStore()
const view = computed(() => route.query.view === 'planes' ? 'planes' : 'membresias')
const query = computed(() => ({ q: String(route.query.q || ''), status: String(route.query.status || ''), sort: String(route.query.sort || ''), direction: route.query.direction === 'asc' ? 'asc' : 'desc', page: Math.max(1, Number(route.query.page || 1)), per_page: 20 }))
const drawer = ref(''); const saving = ref(false); const error = ref(''); const fields = ref({}); const toast = reactive({ open: false, title: '', message: '', tone: 'success' })
const membershipForm = reactive({ usuario_id: '', plan_id: '', fecha_inicio: new Date().toISOString().slice(0, 10), motivo: 'Alta administrativa de membresía' })
const transitionForm = reactive({ id: null, member: '', current: '', estado: 'suspendida', motivo: '' })
const planForm = reactive({ id: null, nombre: '', descripcion: '', duracion_dias: 30, precio: '', moneda: 'UYU', beneficios: '', estado: 'borrador' })
const canWrite = computed(() => admin.hasPermission('memberships.write'))
const memberOptions = computed(() => [{ value: '', label: 'Seleccioná un socio' }, ...members.items.filter((item) => item.estado_socio === 'activo').map((item) => ({ value: item.id, label: `${item.nombre} ${item.apellido} · ${item.email}` }))])
const planOptions = computed(() => [{ value: '', label: 'Seleccioná un plan' }, ...management.plans.filter((item) => item.estado === 'activo').map((item) => ({ value: item.id, label: `${item.nombre} · ${money(item.precio, item.moneda)}` }))])
const membershipColumns = [{ key: 'usuario_nombre', label: 'Socio', sortable: true }, { key: 'usuario_email', label: 'Correo' }, { key: 'plan', label: 'Plan', sortable: true }, { key: 'numero_socio', label: 'N.º socio' }, { key: 'estado', label: 'Estado', format: 'status', sortable: true }, { key: 'fecha_inicio', label: 'Inicio', format: 'date' }, { key: 'fecha_vencimiento', label: 'Vencimiento', format: 'date', sortable: true }, { key: 'precio_pagado', label: 'Importe', format: 'money', currencyKey: 'moneda' }]
const planColumns = [{ key: 'nombre', label: 'Plan' }, { key: 'version', label: 'Versión' }, { key: 'duracion_dias', label: 'Días' }, { key: 'precio', label: 'Precio', format: 'money', currencyKey: 'moneda' }, { key: 'moneda', label: 'Moneda' }, { key: 'estado', label: 'Estado', format: 'status' }, { key: 'actualizado_en', label: 'Actualizado', format: 'datetime' }]
const filters = [{ key: 'status', label: 'Estado', options: [{ value: '', label: 'Todos' }, { value: 'activa', label: 'Activas' }, { value: 'suspendida', label: 'Suspendidas' }, { value: 'vencida', label: 'Vencidas' }] }]
const planFilters = [{ key: 'status', label: 'Estado', options: [{ value: '', label: 'Todos' }, { value: 'borrador', label: 'Borradores' }, { value: 'activo', label: 'Activos' }, { value: 'archivado', label: 'Archivados' }] }]
function money(value, currency = 'UYU') { return new Intl.NumberFormat('es-UY', { style: 'currency', currency }).format(Number(value || 0)) }
function notify(title, message = '', tone = 'success') { Object.assign(toast, { open: true, title, message, tone }) }
function split(value) { return String(value || '').split(',').map((item) => item.trim()).filter(Boolean) }
function update(next) { router.replace({ query: { ...Object.fromEntries(Object.entries(next).filter(([, value]) => value !== '' && value !== null && value !== undefined)), ...(view.value === 'planes' ? { view: 'planes' } : {}) } }) }
function clear() { router.replace({ query: view.value === 'planes' ? { view: 'planes' } : {} }) }
function setView(value) { router.replace({ query: value === 'planes' ? { view: 'planes' } : {} }) }
async function load() { if (view.value === 'planes') await management.loadPlans(query.value); else await memberships.load(query.value); if (canWrite.value) { await Promise.all([members.load({ page: 1, per_page: 50, status: 'activo' }), management.loadPlans({ page: 1, per_page: 50 })]) } }
function openCreateMembership() { Object.assign(membershipForm, { usuario_id: '', plan_id: '', fecha_inicio: new Date().toISOString().slice(0, 10), motivo: 'Alta administrativa de membresía' }); error.value = ''; fields.value = {}; drawer.value = 'membership' }
function openPlan(item = null) { Object.assign(planForm, item ? { id: item.id, nombre: item.nombre, descripcion: item.descripcion || '', duracion_dias: item.duracion_dias, precio: item.precio, moneda: item.moneda, beneficios: (item.beneficios || []).join(', '), estado: item.estado } : { id: null, nombre: '', descripcion: '', duracion_dias: 30, precio: '', moneda: 'UYU', beneficios: '', estado: 'borrador' }); error.value = ''; fields.value = {}; drawer.value = 'plan' }
function openTransition(item) { Object.assign(transitionForm, { id: item.id, member: item.usuario_nombre, current: item.estado, estado: item.estado === 'activa' ? 'suspendida' : 'activa', motivo: '' }); error.value = ''; drawer.value = 'transition' }
async function createMembership() { saving.value = true; const result = await management.createMembership({ ...membershipForm, usuario_id: Number(membershipForm.usuario_id), plan_id: Number(membershipForm.plan_id) }); saving.value = false; if (!result.ok) { error.value = result.message; fields.value = result.fields; return } drawer.value = ''; await load(); notify('Membresía creada', 'La vigencia y el historial quedaron registrados.') }
async function savePlan() { saving.value = true; const result = await management.savePlan({ ...planForm, beneficios: split(planForm.beneficios) }, planForm.id); saving.value = false; if (!result.ok) { error.value = result.message; fields.value = result.fields; return } drawer.value = ''; await management.loadPlans(query.value); notify(result.meta?.versioned ? 'Nueva versión creada' : 'Plan guardado', result.meta?.versioned ? 'La versión usada quedó archivada para conservar trazabilidad.' : '') }
async function transition() { saving.value = true; const result = await management.transitionMembership(transitionForm.id, { estado: transitionForm.estado, motivo: transitionForm.motivo }); saving.value = false; if (!result.ok) { error.value = result.message; fields.value = result.fields; return } drawer.value = ''; await memberships.load(query.value); notify('Estado actualizado', `La membresía de ${transitionForm.member} quedó ${transitionForm.estado}.`) }
watch([() => route.query, () => admin.version], load, { immediate: true, deep: true })
onBeforeUnmount(() => { memberships.cancel(); members.cancel() })
</script>

<template>
  <section>
    <AdminPageHeading title="Membresías" description="Planes versionados, altas y cambios de estado con historial por gimnasio."><template v-if="canWrite" #actions><AppButton @click="view === 'planes' ? openPlan() : openCreateMembership()"><template #icon><IconPlus :size="18" /></template>{{ view === 'planes' ? 'Crear plan' : 'Crear membresía' }}</AppButton></template></AdminPageHeading>
    <nav class="view-tabs" aria-label="Secciones de membresías"><button type="button" :aria-current="view === 'membresias' ? 'page' : undefined" @click="setView('membresias')">Membresías</button><button type="button" :aria-current="view === 'planes' ? 'page' : undefined" @click="setView('planes')">Planes</button></nav>
    <AppCard :padded="false" class="resource-card">
      <template v-if="view === 'membresias'"><AdminFilterBar :model-value="query" :filters="filters" :loading="memberships.status === 'loading'" @apply="update" @clear="clear" /><AdminDataTable :columns="membershipColumns" :items="memberships.items" :pagination="memberships.pagination" :status="memberships.status" :error="memberships.error" :sort="query.sort" :direction="query.direction" empty-title="No hay membresías" empty-description="Creá una membresía cuando exista al menos un socio y un plan activo." :row-action-label="canWrite ? 'Cambiar estado' : ''" @sort="update({ ...query, sort: $event, page: 1 })" @page="update({ ...query, page: $event })" @retry="memberships.load(query)" @row="openTransition" /></template>
      <template v-else><AdminFilterBar :model-value="query" :filters="planFilters" :loading="management.status === 'loading'" @apply="update" @clear="clear" /><AdminDataTable :columns="planColumns" :items="management.plans" :pagination="management.plansPagination" :status="management.status === 'loading' ? 'loading' : management.error ? 'error' : management.plans.length ? 'ready' : 'empty'" :error="management.error" empty-title="No hay planes" empty-description="Creá el primer plan comercial del gimnasio." :row-action-label="canWrite ? 'Editar' : ''" @page="update({ ...query, page: $event })" @retry="management.loadPlans(query)" @row="openPlan" /></template>
    </AppCard>

    <AppDrawer :open="drawer === 'membership'" title="Crear membresía" @close="drawer = ''"><form id="membership-create-form" class="form" @submit.prevent="createMembership"><AppAlert v-if="error" tone="danger" title="No pudimos crear la membresía"><p>{{ error }}</p></AppAlert><div class="form-note"><IconIdBadge2 :size="22" /><p>La fecha de vencimiento se calcula desde la duración versionada del plan.</p></div><AppSelect v-model="membershipForm.usuario_id" label="Socio" name="membership-member" :options="memberOptions" :error="fields.usuario_id" /><AppSelect v-model="membershipForm.plan_id" label="Plan" name="membership-plan" :options="planOptions" :error="fields.plan_id" /><AppInput v-model="membershipForm.fecha_inicio" label="Fecha de inicio" name="membership-start" type="date" required :error="fields.fecha_inicio" /><AppTextarea v-model="membershipForm.motivo" label="Motivo" name="membership-reason" :rows="3" :error="fields.motivo" /></form><template #footer><div class="actions"><AppButton variant="secondary" @click="drawer = ''">Cancelar</AppButton><AppButton type="submit" form="membership-create-form" :loading="saving">Crear membresía</AppButton></div></template></AppDrawer>
    <AppDrawer :open="drawer === 'plan'" :title="planForm.id ? 'Editar plan' : 'Crear plan'" @close="drawer = ''"><form id="plan-form" class="form" @submit.prevent="savePlan"><AppAlert v-if="error" tone="danger" title="No pudimos guardar el plan"><p>{{ error }}</p></AppAlert><AppInput v-model="planForm.nombre" label="Nombre" name="plan-name" required :error="fields.nombre" /><AppTextarea v-model="planForm.descripcion" label="Descripción" name="plan-description" :rows="3" :error="fields.descripcion" /><div class="form-grid"><AppInput v-model="planForm.duracion_dias" label="Duración en días" name="plan-days" type="number" required :error="fields.duracion_dias" /><AppInput v-model="planForm.precio" label="Precio" name="plan-price" inputmode="decimal" required :error="fields.precio" /></div><AppSelect v-model="planForm.moneda" label="Moneda" name="plan-currency" :options="[{ value: 'UYU', label: 'UYU' }, { value: 'USD', label: 'USD' }]" /><AppInput v-model="planForm.beneficios" label="Beneficios" name="plan-benefits" hint="Separados por comas." /><AppSelect v-model="planForm.estado" label="Estado" name="plan-status" :options="[{ value: 'borrador', label: 'Borrador' }, { value: 'activo', label: 'Activo' }, { value: 'archivado', label: 'Archivado' }]" /></form><template #footer><div class="actions"><AppButton variant="secondary" @click="drawer = ''">Cancelar</AppButton><AppButton type="submit" form="plan-form" :loading="saving">Guardar plan</AppButton></div></template></AppDrawer>
    <AppDrawer :open="drawer === 'transition'" title="Cambiar estado" @close="drawer = ''"><form id="membership-transition-form" class="form" @submit.prevent="transition"><AppAlert v-if="error" tone="danger" title="No pudimos cambiar el estado"><p>{{ error }}</p></AppAlert><p class="member-name">{{ transitionForm.member }} · estado actual: {{ transitionForm.current }}</p><AppSelect v-model="transitionForm.estado" label="Nuevo estado" name="membership-status" :options="[{ value: 'activa', label: 'Activa' }, { value: 'suspendida', label: 'Suspendida' }, { value: 'vencida', label: 'Vencida' }]" /><AppTextarea v-model="transitionForm.motivo" label="Motivo" name="membership-status-reason" :rows="3" :error="fields.motivo" /></form><template #footer><div class="actions"><AppButton variant="secondary" @click="drawer = ''">Cancelar</AppButton><AppButton type="submit" form="membership-transition-form" :loading="saving">Confirmar cambio</AppButton></div></template></AppDrawer>
    <AppToast v-bind="toast" @close="toast.open = false" />
  </section>
</template>

<style scoped>
.view-tabs { display: flex; gap: var(--space-1); margin: var(--space-6) 0 var(--space-4); border-bottom: 1px solid var(--border-subtle); }.view-tabs button { min-height: 2.75rem; border: 0; border-bottom: 2px solid transparent; padding: 0 var(--space-4); background: transparent; color: var(--text-secondary); cursor: pointer; font: inherit; font-size: .82rem; font-weight: 700; }.view-tabs button:hover { color: var(--text-primary); }.view-tabs button[aria-current="page"] { border-bottom-color: var(--accent); color: var(--status-info-strong); }.resource-card { overflow: clip; }.form { display: grid; gap: var(--space-5); }.form-grid { display: grid; grid-template-columns: 1fr 1fr; gap: var(--space-3); }.form-note { display: grid; grid-template-columns: 1.5rem 1fr; gap: var(--space-3); border-bottom: 1px solid var(--border-subtle); padding-bottom: var(--space-5); }.form-note svg { color: var(--info); }.form-note p,.member-name { margin: 0; color: var(--text-secondary); font-size: .8rem; line-height: 1.5; }.actions { display: flex; justify-content: flex-end; gap: var(--space-3); }
@media (max-width: 30rem) { .form-grid { grid-template-columns: 1fr; }.actions { display: grid; grid-template-columns: 1fr 1fr; } }
</style>
