<!--
  Vista de ruta ChangePasswordView. Coordina componentes, estado reactivo y llamadas a la API para completar este flujo de usuario.
  En <script> se declaran imports, estado y funciones; <template> describe la interfaz y <style> limita su presentación.
-->
<script setup>
import { reactive, ref } from 'vue';import {useRouter} from 'vue-router';import AuthShell from '../components/auth/AuthShell.vue';import AppAlert from '../components/ui/AppAlert.vue';import AppButton from '../components/ui/AppButton.vue';import AppInput from '../components/ui/AppInput.vue';import {api} from '../services/api';import {useAuthStore} from '../stores/auth'
const router=useRouter();const auth=useAuthStore();const form=reactive({current_password:'',password:'',password_confirmation:'',logout_other_sessions:true});const loading=ref(false);const error=ref('');const success=ref('')
async function submit(){if(loading.value)return;if(form.password!==form.password_confirmation){error.value='Las contraseñas nuevas no coinciden.';return}loading.value=true;error.value='';const response=await api.post('/auth/password/change',form);loading.value=false;if(!response.ok){if(response.status===401){auth.limpiarSesionLocal();await router.push({name:'session-expired'});return}error.value=response.data.mensaje;return}success.value=response.data.mensaje;await auth.bootstrap(true)}
</script>
<template><AuthShell><template #title>Cambiá tu contraseña</template><template #description>Confirmá la contraseña actual y elegí una nueva. Podés cerrar el resto de tus sesiones.</template><AppAlert v-if="auth.user?.must_change_password" tone="warning" title="Cambio requerido"><p>Debés actualizar esta contraseña antes de continuar.</p></AppAlert><AppAlert v-if="error" tone="danger" title="No pudimos cambiarla"><p>{{error}}</p></AppAlert><AppAlert v-if="success" tone="success" title="Cambio guardado"><p>{{success}}</p><p><RouterLink :to="{name:'dashboard'}">Volver al panel</RouterLink></p></AppAlert><form v-if="!success" class="form" @submit.prevent="submit"><AppInput v-model="form.current_password" label="Contraseña actual" type="password" autocomplete="current-password" maxlength="200" required :disabled="loading"/><AppInput v-model="form.password" label="Nueva contraseña" type="password" autocomplete="new-password" minlength="12" maxlength="200" hint="12 caracteres, con mayúscula, minúscula y número." required :disabled="loading"/><AppInput v-model="form.password_confirmation" label="Confirmar contraseña" type="password" autocomplete="new-password" minlength="12" maxlength="200" required :disabled="loading"/><label class="check"><input v-model="form.logout_other_sessions" type="checkbox"/><span>Cerrar mis otras sesiones al guardar.</span></label><AppButton type="submit" block :loading="loading">Actualizar contraseña</AppButton></form><template #footer><RouterLink v-if="!auth.user?.must_change_password" :to="{name:'dashboard'}">Cancelar y volver al panel</RouterLink></template></AuthShell></template>
<style scoped>.form{display:grid;gap:var(--space-5)}.check{display:flex;align-items:flex-start;gap:var(--space-3);color:var(--text-secondary);font-size:.85rem}.check input{width:1.1rem;height:1.1rem;accent-color:var(--accent)}.alert a{color:var(--status-info-strong)}</style>
