<script setup>
import { nextTick,onBeforeUnmount,onMounted,reactive,ref } from 'vue';import AuthShell from '../components/auth/AuthShell.vue';import AppAlert from '../components/ui/AppAlert.vue';import AppButton from '../components/ui/AppButton.vue';import AppInput from '../components/ui/AppInput.vue';import {useAuthStore} from '../stores/auth';import {useSystemStore} from '../stores/system'
const auth=useAuthStore();const system=useSystemStore();const loading=ref(false);const error=ref('');const success=ref('');const fields=ref({});const form=reactive({nombre:'',apellido:'',email:'',gym_name:'',message:'',password:'',password_confirmation:'',terms_accepted:false,privacy_accepted:false,marketing_accepted:false});const turnstileEl=ref(null);const token=ref('');let widget=null;let poll=null
function render(){if(!system.turnstileEnabled||!window.turnstile||!turnstileEl.value||widget!==null)return;widget=window.turnstile.render(turnstileEl.value,{sitekey:system.turnstileSiteKey,theme:'dark',callback:value=>{token.value=value},'expired-callback':()=>{token.value=''}})}
async function submit(){if(loading.value)return;error.value='';fields.value={};if(form.password!==form.password_confirmation){fields.value={password_confirmation:'Las contraseñas no coinciden.'};return}if(system.turnstileEnabled&&!token.value){error.value='Completá la verificación anti robot.';return}loading.value=true;try{const data=await auth.registro({...form,turnstileToken:token.value},true);success.value=data.mensaje}catch(failure){error.value=failure.message;fields.value=failure.fields||{};if(window.turnstile&&widget!==null)window.turnstile.reset(widget)}finally{loading.value=false}}
onMounted(async()=>{if(!system.loaded)await system.load();await nextTick();if(system.turnstileEnabled)poll=window.setInterval(()=>{render();if(widget!==null){window.clearInterval(poll);poll=null}},250)});onBeforeUnmount(()=>{if(poll!==null)window.clearInterval(poll);if(window.turnstile&&widget!==null)window.turnstile.remove(widget)})
</script>
<template><AuthShell><template #title>Solicitá acceso para tu gimnasio</template><template #description>La solicitud crea una cuenta sin permisos operativos. Un administrador debe revisar y vincular el gimnasio.</template><AppAlert v-if="error" tone="danger" title="Revisá la solicitud"><p>{{error}}</p></AppAlert><AppAlert v-if="success" tone="success" title="Solicitud recibida"><p>{{success}}</p><p><RouterLink :to="{name:'verify-email',query:{email:form.email}}">Verificar correo</RouterLink></p></AppAlert><form v-if="!success" class="form" @submit.prevent="submit"><div class="grid"><AppInput v-model.trim="form.nombre" label="Nombre" autocomplete="given-name" minlength="2" maxlength="100" required :error="fields.nombre"/><AppInput v-model.trim="form.apellido" label="Apellido" autocomplete="family-name" minlength="2" maxlength="100" required :error="fields.apellido"/></div><AppInput v-model.trim="form.email" label="Correo electrónico" type="email" autocomplete="email" maxlength="150" required :error="fields.email"/><AppInput v-model.trim="form.gym_name" label="Nombre del gimnasio" autocomplete="organization" maxlength="120" required :error="fields.gym_name"/><AppInput v-model="form.password" label="Contraseña" type="password" autocomplete="new-password" minlength="12" maxlength="200" hint="12 caracteres, con mayúscula, minúscula y número." required :error="fields.password"/><AppInput v-model="form.password_confirmation" label="Confirmar contraseña" type="password" autocomplete="new-password" minlength="12" maxlength="200" required :error="fields.password_confirmation"/><label class="check"><input v-model="form.terms_accepted" type="checkbox" required/><span>Acepto los <RouterLink to="/terminos">términos de uso</RouterLink>.</span></label><label class="check"><input v-model="form.privacy_accepted" type="checkbox" required/><span>Acepto la <RouterLink to="/privacidad">política de privacidad</RouterLink>.</span></label><label class="check optional"><input v-model="form.marketing_accepted" type="checkbox"/><span>Quiero recibir novedades. Es opcional.</span></label><div v-if="system.turnstileEnabled" ref="turnstileEl" class="turnstile"></div><AppButton type="submit" block :loading="loading">Enviar solicitud</AppButton></form><template #footer>¿Buscás una cuenta de socio? <RouterLink :to="{name:'registro'}">Registrate como socio</RouterLink></template></AuthShell></template>
<style scoped>.form{display:grid;gap:var(--space-4)}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:var(--space-4)}.check{display:flex;align-items:flex-start;gap:var(--space-3);color:var(--text-secondary);font-size:.8rem}.check input{width:1.1rem;height:1.1rem;accent-color:var(--accent)}.check a,.alert a{color:var(--status-info-strong)}.optional{color:var(--text-tertiary)}.turnstile{min-height:4rem}@media(max-width:29.99rem){.grid{grid-template-columns:1fr}}</style>
