<!--
  Vista de ruta SessionsView. Coordina componentes, estado reactivo y llamadas a la API para completar este flujo de usuario.
  En <script> se declaran imports, estado y funciones; <template> describe la interfaz y <style> limita su presentación.
-->
<script setup>
import { onMounted, ref } from 'vue';import {useRouter} from 'vue-router';import {IconDeviceLaptop,IconLogout} from '@tabler/icons-vue';import AuthShell from '../components/auth/AuthShell.vue';import AppAlert from '../components/ui/AppAlert.vue';import AppButton from '../components/ui/AppButton.vue';import AppSkeleton from '../components/ui/AppSkeleton.vue';import {api} from '../services/api';import {useAuthStore} from '../stores/auth'
const router=useRouter();const auth=useAuthStore();const sessions=ref([]);const loading=ref(true);const error=ref('');const busy=ref('')
async function load(){loading.value=true;const response=await api.get('/me/sessions');loading.value=false;if(response.ok)sessions.value=response.data.sessions;else error.value=response.data.mensaje}
async function revoke(id){busy.value=id;const response=await api.delete(`/me/sessions/${id}`);busy.value='';if(response.ok)await load();else error.value=response.data.mensaje}
async function logoutAll(){busy.value='all';await auth.logoutAll();await router.push({name:'login'})}
onMounted(load)
</script>
<template><AuthShell><template #title>Sesiones activas</template><template #description>Revisá los dispositivos con acceso y cerrá cualquiera que no reconozcas.</template><AppAlert v-if="error" tone="danger" title="No pudimos cargar las sesiones"><p>{{error}}</p></AppAlert><div v-if="loading" class="session-list" aria-label="Cargando sesiones"><AppSkeleton v-for="n in 2" :key="n" height="6rem"/></div><div v-else class="session-list"><article v-for="session in sessions" :key="session.id" class="session"><IconDeviceLaptop :size="22"/><div><h2>{{session.device}}</h2><p>Última actividad: {{session.last_activity_at}}</p><strong v-if="session.current">Sesión actual</strong></div><AppButton v-if="!session.current" variant="secondary" size="sm" :loading="busy===session.id" @click="revoke(session.id)">Revocar</AppButton></article></div><AppButton class="logout-all" variant="danger" block :loading="busy==='all'" @click="logoutAll"><template #icon><IconLogout :size="18"/></template>Cerrar todas las sesiones</AppButton><template #footer><RouterLink :to="{name:'dashboard'}">Volver al panel</RouterLink></template></AuthShell></template>
<style scoped>.session-list{display:grid;gap:var(--space-3)}.session{display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:var(--space-4);border-bottom:1px solid var(--border-subtle);padding:var(--space-4) 0}.session svg{color:var(--info)}.session h2{margin:0 0 var(--space-1);font-size:1rem}.session p,.session strong{margin:0;color:var(--text-secondary);font-size:.75rem}.session strong{color:var(--status-success-strong)}.logout-all{margin-top:var(--space-8)}@media(max-width:29.99rem){.session{grid-template-columns:auto 1fr}.session button{grid-column:1/-1;width:100%}}</style>
