<script setup>
import { onMounted, reactive, ref } from 'vue';import {useRoute,useRouter} from 'vue-router';import AuthShell from '../components/auth/AuthShell.vue';import AppAlert from '../components/ui/AppAlert.vue';import AppButton from '../components/ui/AppButton.vue';import AppInput from '../components/ui/AppInput.vue';import {api} from '../services/api';import {useAuthStore} from '../stores/auth'
const route=useRoute();const router=useRouter();const auth=useAuthStore();const form=reactive({email:String(route.query.email||auth.user?.email||'')});const state=ref(route.query.token?'verifying':'idle');const message=ref('');const error=ref('');const loading=ref(false)
async function verify(){const token=String(route.query.token||'');if(!token)return;const response=await api.post('/auth/email/verify',{token});if(response.ok){state.value='success';message.value=response.data.mensaje;if(auth.estaAutenticado)await auth.bootstrap(true)}else{state.value='error';error.value=response.data.mensaje}}
async function resend(){if(loading.value)return;loading.value=true;error.value='';const response=await api.post('/auth/email/resend',{email:form.email});loading.value=false;if(response.ok)message.value=response.data.mensaje;else error.value=response.data.mensaje}
async function continueToApp(){await router.push(auth.estaAutenticado?{name:'dashboard'}:{name:'login'})}
onMounted(verify)
</script>
<template><AuthShell><template #title>Verificá tu correo</template><template #description>La verificación confirma que la dirección te pertenece y habilita las rutas protegidas.</template><AppAlert v-if="state==='verifying'" tone="info" title="Validando enlace"><p>Esperá un momento.</p></AppAlert><AppAlert v-if="message" tone="success" title="Solicitud procesada"><p>{{message}}</p></AppAlert><AppAlert v-if="error" tone="danger" title="El enlace no se pudo usar"><p>{{error}}</p></AppAlert><div v-if="state==='success'" class="actions"><AppButton block @click="continueToApp">Continuar</AppButton></div><form v-else-if="state!=='verifying'" class="form" @submit.prevent="resend"><AppInput v-model.trim="form.email" label="Correo electrónico" type="email" autocomplete="email" maxlength="150" required :disabled="loading"/><AppButton type="submit" block :loading="loading">Reenviar verificación</AppButton></form><template #footer><RouterLink :to="{name:'login'}">Volver a iniciar sesión</RouterLink></template></AuthShell></template>
<style scoped>.form,.actions{display:grid;gap:var(--space-5);margin-top:var(--space-5)}</style>
